usersvc:
  endpoints:
    - http://ec2s-usersvc-02.mypna.com:8080|stage,na
    - http://ec2s-euusersvc-01.mypna.com:8080|stage,eu
    - http://alish2s-autodenali-ums-service-01.mypna.cn:8080|stage,cn
    - http://ec1-usersvc-01.ec1.mypna.com:8080|prod,na
    - http://ec1-usersvc-02.ec1.mypna.com:8080|prod,na
    - http://ec1-usersvc-03.ec1.mypna.com:8080|prod,na
    - http://ec1-usersvc-04.ec1.mypna.com:8080|prod,na
    - http://ec2-usersvc-01.ec2.mypna.com:8080|prod,na
    - http://ec2-usersvc-02.ec2.mypna.com:8080|prod,na
    - http://ec2-usersvc-03.ec2.mypna.com:8080|prod,na
    - http://ec6-usersvc-01.ec6.mypna.com:8080|prod,eu
    - http://ec6-usersvc-02.ec6.mypna.com:8080|prod,eu
    - http://ec6-usersvc-03.ec6.mypna.com:8080|prod,eu
  apis:
    - /user/version
    - /user/v6/identity/login
    - /user/v6/identity/register_login
    - /user/v6/identity/change_password
    - /user/v6/identity/logout
    - /user/v6/identity/ask_for_delete
    - /user/v6/identity/validate_verification
    - /user/v6/subscription/save
    - /user/v6/identity/delete_account
    - /user/v6/receipt
    - /user/v6/identity/add_credentials
    - /user/v6/identity/find
    - /user/v6/client_data/import
    - /user/v6/client_data/translate
    - /user/v6/connection/add
    - /user/v6/connection/setup
    - /user/v6/contact/search
    - /user/v6/contact/upload
    - /user/v6/feedback
    - /user/v6/identity/apply_verification
    - /user/v6/item/mark
    - /user/v6/item/unmark
    - /user/v6/items
    - /user/v6/marker/save
    - /user/v6/marker/remove
    - /user/v6/markers
    - /user/v6/media/storage_url
    - /user/v6/profile/save
    - /user/v6/profiles
    - /user/v6/public_favorites
    - /user/v6/merchant_account/save
    - /user/v6/sync
    - /user/v6/merchant_accounts
    - /user/v6/identity/register
    - /user/v6/identity/password_reset_token
    - /user/v6/identity/session
    - /user/v6/identity/refresh
    - /user/v6/app/validate
    - /user/v6/connections
